# Generated by Django 4.0.3 on 2022-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('sent for approval', 'Отправлено на согласование'), ('accepted', 'Согласовано')], default='sent for approval', max_length=17),
        ),
    ]
